apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandobook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mandobook-ui
  template:
    metadata:
      labels:
        app: mandobook-ui
    spec:
      containers:
      - image: docker.io/bitnami/apache
        name: mandobook-ui
        ports:
        - containerPort: 80
